version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build --prod
  post_build:
    commands:
      - aws s3 sync --delete ./dist/blocklyflask-frontend s3://$BUCKET_NAME
artifacts:
  files:
    - '**/*'
  base-directory: dist/blocklyflask-frontend
